### ISSUE TITLE
训练时bce_loss计算错误

### ISSUE THREAD

**Issue by 2014587647** [TongfeiLiu/C3Net-for-building-extraction#2]
训练时，在bce_Loss = BCE_loss(pred1, label)报错，查看之后label是([2, 1, 256, 256])，pred1是([2, 2, 256, 256])，请问怎么解决这个问题啊

**Comment by TongfeiLiu** [comment]
请检查train.py文件中，初始化网珞结构时n_classes应当设置为1。
